Add index page
oSoc19/gentlestudent-web pull request #93
Opened 2020-05-18 14:17 UTC by hektormisplon

2020-05-18 15:14 UTC, archived-m requested changes

2020-05-18 15:14 UTC, archived-m commented on v2/components/UI/card.jsx
> +          box-shadow: 0 0.5rem 1rem 2px rgba(0, 0, 0, 0.1);
Mixing pixel and rem values here
```suggestion
          box-shadow: 0 0.5rem 1rem 0.2rem rgba(0, 0, 0, 0.1);
```

2020-05-18 15:14 UTC, archived-m commented on v2/components/UI/card.jsx
> +          font-size: 80%;
Let's use pre-determined and constant rem-values to avoid having many different font-size across all pages in the future

2020-05-18 15:14 UTC, archived-m commented on v2/components/UI/card.jsx
> +    <img src={image} />
An image should always have an alt text https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/alt-text.md
Perhaps we can pass it in as additional prop to `Card`?

2020-05-18 15:14 UTC, archived-m commented on v2/components/UI/card.jsx
> +};
Missing prop types, which one of these are required?

```suggestion
Card.propTypes = {
  image: PropTypes.string,
  title: PropTypes.string,
  description: PropTypes.string,
  onClick: PropTypes.func,
  date: PropTypes.string
};
```

2020-05-18 15:14 UTC, archived-m commented on v2/components/download.jsx
> +    <img src={mockup} alt="mockup" />
```suggestion
    <img src={mockup} alt="Gentlestudent app being used on a smartphone" />
```

2020-05-18 15:14 UTC, archived-m commented on v2/components/download.jsx
> +          <img src={ios} alt="download-button-ios" />
```suggestion
          <img src={ios} alt="iOS download button" />
```

2020-05-18 15:14 UTC, archived-m commented on v2/components/download.jsx
> +          <img src={android} alt="download-button-android" />
```suggestion
          <img src={android} alt="Android download button" />
```

2020-05-18 15:14 UTC, archived-m commented on v2/assets/styles/global.js
> +    scroll-snap-type: y mandatory;
Cool, did not know this existed. Let's ask around when this is deployed to see if this is desired behaviour though

2020-05-18 15:14 UTC, MichielLeyman commented on v2/components/download.jsx
> +          }
Indentation is off here

2020-05-18 15:14 UTC, MichielLeyman commented on v2/components/introVideo.jsx
> +    />
The video player does not look the same as on the original version - specifically the fit of the video. I'd copy this from v1

2020-05-18 15:19 UTC, archived-m requested changes
1. Personal preference:
The download and introvideo sections are not reusable and small enough to be in the index page itself in my opinion. If you'd prefer them to be isolated components, let's put them in a `home` or `index` folder.
2. The "news" section is taller than the original
3. The download sections is not full width, like in the original.
4. The `eyecatcher` and `what-new` images are too big (922KB and 1.4MB). Let's resize and compress them

2020-05-19 08:47 UTC, hektormisplon commented
Moved to [#94 ](https://github.com/Gentlestudent/web-app/pull/94)

2020-05-19 08:47 UTC, closed without merging